#!/usr/bin/env python3
"""Single parameter loader shared by Blender and ROS asset generation (SI units)."""
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load_parameters(root=ROOT):
    raw = (Path(root) / 'config/amr_dimensions.json').read_bytes()
    p = json.loads(raw)
    for key, value in p.items():
        if isinstance(value, (float, int)) and (not math.isfinite(value) or value <= 0):
            raise ValueError(f'{key} must be positive and finite')
    p['config_sha256'] = hashlib.sha256(raw).hexdigest()
    p['chassis_z'] = p['ground_clearance'] + p['chassis_height'] / 2
    p['chassis_top'] = p['ground_clearance'] + p['chassis_height']
    p['platform_z'] = p['chassis_top'] + p['platform_gap'] + p['platform_thickness'] / 2
    p['overall_height'] = p['platform_z'] + p['platform_thickness'] / 2
    p['wheel_y'] = p['track_width'] / 2
    p['wheel_z'] = p['wheel_radius']
    p['arch_half_length'] = p['wheel_radius'] + p['wheel_arch_gap']
    p['arch_top'] = 2 * p['wheel_radius'] + p['wheel_arch_gap']
    p['core_half_width'] = p['wheel_y'] - p['wheel_width'] / 2 - p['wheel_arch_gap']
    p['caster_x'] = p['chassis_length'] / 2 - p['caster_end_inset']
    p['bumper_x'] = (p['chassis_length'] - p['bumper_length']) / 2
    p['bumper_z'] = p['ground_clearance'] + p['bumper_bottom_gap'] + p['bumper_height'] / 2
    p['bay_z'] = p['ground_clearance'] + p['chassis_height'] * p['sensor_bay_z_fraction']
    p['bay_bottom'] = p['bay_z'] - p['sensor_bay_height'] / 2
    p['bay_top'] = p['bay_z'] + p['sensor_bay_height'] / 2
    p['bay_back_x'] = p['chassis_length'] / 2 - p['sensor_bay_depth']
    p['lidar_x'] = p['chassis_length'] / 2 - p['lidar_radius']
    p['lidar_z'] = p['bay_bottom'] + p['lidar_height'] / 2
    p['laser_z'] = p['lidar_z'] + p['lidar_height'] / 2 + p['lidar_scan_gap']
    p['camera_x'] = (p['chassis_length'] - p['camera_length']) / 2
    p['camera_z'] = p['chassis_top'] - p['camera_top_margin'] - p['camera_height'] / 2
    p['lidar_half_fov'] = math.radians(p['lidar_fov_degrees']) / 2
    p['camera_fov'] = math.radians(p['camera_fov_degrees'])
    p['core_length'] = p['bay_back_x'] + p['chassis_length'] / 2
    p['core_x'] = -p['sensor_bay_depth'] / 2
    p['end_collision_width'] = p['chassis_width'] - 2 * p['chassis_corner_radius']
    p['front_collision_length'] = p['bay_back_x'] - p['arch_half_length']
    p['front_collision_x'] = (p['bay_back_x'] + p['arch_half_length']) / 2
    p['rear_collision_length'] = p['chassis_length'] / 2 - p['arch_half_length'] - p['chassis_bevel']
    p['rear_collision_x'] = -p['arch_half_length'] - p['rear_collision_length'] / 2
    checks = {
        'wheel pockets must leave a chassis roof': p['arch_top'] < p['chassis_top'] - p['chassis_bevel'],
        'wheel track must fit chassis': p['wheel_y'] + p['wheel_width']/2 < p['chassis_width']/2,
        'positive chassis core': p['core_half_width'] > 0,
        'platform must fit chassis': p['platform_length'] < p['chassis_length'] and p['platform_width'] < p['chassis_width'],
        'front collision clear of wheels': p['front_collision_length'] > 0,
        'scanner must fit open bay': p['laser_z'] < p['bay_top'] and 2*p['lidar_radius'] < p['sensor_bay_depth'],
        'camera must sit above bay': p['camera_z']-p['camera_height']/2 > p['bay_top'],
        'casters must clear wheel axle': p['caster_x']-p['caster_radius'] > p['arch_half_length'],
        'casters must reach chassis': 2*p['caster_radius'] > p['ground_clearance'],
        'low COM inside chassis': p['ground_clearance'] < p['chassis_com_height'] < p['chassis_top'],
        'front lidar FOV must avoid rear chassis': p['lidar_fov_degrees'] <= 180,
    }
    for label, ok in checks.items():
        if not ok:
            raise ValueError(label)
    return p


def write_ros_parameters(root=ROOT):
    root = Path(root)
    p = load_parameters(root)
    lines = ['<?xml version="1.0"?>', '<!-- Generated by scripts/amr_parameters.py; edit amr_dimensions.json. -->',
             '<robot xmlns:xacro="http://www.ros.org/wiki/xacro">']
    for key, value in p.items():
        if isinstance(value, (int, float)):
            lines.append(f'  <xacro:property name="{key}" value="{value:.12g}"/>')
        elif isinstance(value, list):
            lines.append(f'  <xacro:property name="{key}" value="{chr(32).join(str(v) for v in value)}"/>')
    lines.append('</robot>\n')
    (root/'urdf/dimensions.xacro').write_text('\n'.join(lines))
    # JSON is a YAML subset, accepted by ROS parameters and xacro.load_yaml.
    controllers = {
        'controller_manager': {'ros__parameters': {
            'update_rate': p['controller_rate'], 'use_sim_time': True, 'enforce_command_limits': True,
            'joint_state_broadcaster': {'type': 'joint_state_broadcaster/JointStateBroadcaster'},
            'diff_drive_controller': {'type': 'diff_drive_controller/DiffDriveController'}}},
        'diff_drive_controller': {'ros__parameters': {
            'left_wheel_names': ['left_wheel_joint'], 'right_wheel_names': ['right_wheel_joint'],
            'wheel_separation': p['track_width'], 'wheel_radius': p['wheel_radius'],
            'base_frame_id': 'base_link', 'odom_frame_id': 'odom', 'enable_odom_tf': True,
            'position_feedback': True, 'open_loop': False, 'publish_rate': 50.0,
            'cmd_vel_timeout': p['command_timeout'],
            'pose_covariance_diagonal': [0.001, 0.001, 0.001, 0.001, 0.001, 0.01],
            'twist_covariance_diagonal': [0.001, 0.001, 0.001, 0.001, 0.001, 0.01],
            'linear.x.max_velocity': p['max_linear_velocity'],
            'linear.x.min_velocity': -p['max_linear_velocity'],
            'linear.x.max_acceleration': p['max_linear_acceleration'],
            'linear.x.max_deceleration': -p['max_linear_acceleration'],
            'angular.z.max_velocity': p['max_angular_velocity'],
            'angular.z.min_velocity': -p['max_angular_velocity'],
            'angular.z.max_acceleration': p['max_angular_acceleration'],
            'angular.z.max_deceleration': -p['max_angular_acceleration']}}
    }
    (root/'config/controllers.yaml').write_text(json.dumps(controllers, indent=2)+'\n')
    limits = {'joint_limits': {f'{s}_wheel_joint': {
        'has_velocity_limits': True, 'max_velocity': p['wheel_max_velocity'],
        'has_effort_limits': True, 'max_effort': p['wheel_max_effort']
    } for s in ('left', 'right')}}
    (root/'config/joint_limits.yaml').write_text(json.dumps(limits, indent=2)+'\n')
    return p


if __name__ == '__main__':
    print(json.dumps(write_ros_parameters(), indent=2))
